### ISSUE TITLE
Fail to load microsoft/ApplicationInspector-Action/v1/action.yml

### ISSUE THREAD

**Issue by clement128** [microsoft/ApplicationInspector-Action#3]
Hi there, I am trying ApplicationInspector in Github Action, here is my yml file, very simple, but it doesn't work.  Could anyone help to point out what's the problem? I can't find in the document.

```yml
name: Code scanning

on:
    push:
        branches:
            - "master"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - uses: microsoft/ApplicationInspector-Action@v1
            - uses: actions/upload-artifact@v2
              with:
                  name: AppInspectorResults
                  path: AppInspectorResults.json
```

```logs
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v2'
Download action repository 'github/codeql-action@v1'
Download action repository 'microsoft/ApplicationInspector-Action@v1'
##[error]microsoft/ApplicationInspector-Action/v1/action.yml (Line: 25, Col: 9): Unexpected value ''
##[error]microsoft/ApplicationInspector-Action/v1/action.yml (Line: 25, Col: 9): Unexpected value ''
##[error]System.ArgumentException: Unexpected type 'NullToken' encountered while reading 'outputs'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
##[error]Fail to load microsoft/ApplicationInspector-Action/v1/action.yml
```

Thanks in advance

**Comment by felixro** [comment]
I had the same exact error and created a PR https://github.com/microsoft/ApplicationInspector-Action/pull/4 to resolve the issue.

**Comment by timmay54** [comment]
Same error

**Comment by marwie** [comment]
I have the same error

**Comment by gfs** [comment]
Resolved by merging proposed PR. Sorry for the delay. Please try latest.
